### ISSUE TITLE
Any plans for Vue.JS client?

### ISSUE THREAD

**Issue by vsaroopchand** [microsoft/powerbi-client-react#1]
Do you have plans for other client side libs (Vue.JS, Angular)? If so, how can we contribute since this repo is specifically for React.

**Comment by KotanaSai21** [comment]
Client-side libraries for both Angular and Vuejs are available now. Please find the link below.

[powerbi-client-vue-js](https://github.com/microsoft/powerbi-client-vue-js)
[powerbi-client-angular](https://github.com/microsoft/powerbi-client-angular)
