### ISSUE TITLE
CSS mismatch when report is rendered using powerbi-client-react library

### ISSUE THREAD

**Issue by xeroOrex** [microsoft/powerbi-client-react#101]
We have a power Bi Report which has a mobile layout as well. While rendering the report in our Single Page Application, based on the screen size we render  either **MobilePortrait** or **MobileLandscape**  layout. Now when we render the same report in power bi mobile application and compare the rendering, we see there are few CSS issues.

1. The buttons are missing paddings. PFB the screenshot which compares two different versions of rendering. One is using our SPA and powerbi-client-react lib and the other is using Power Bi mobile application.

Using Powerbi mobile application (Proper css alignment present)
![image](https://github.com/microsoft/powerbi-client-react/assets/53090923/0e2bbd1c-402a-4e26-9f94-9ba216b37886)

using Powerbi-client-reactlib (paddings/margins are missing)
![image](https://github.com/microsoft/powerbi-client-react/assets/53090923/aac0d0b2-3360-4fed-a0cd-7fd245c0f0cc)

2. report texts are not visible properly

using Power bi mobile client app (all texts shows perfectly)
![image](https://github.com/microsoft/powerbi-client-react/assets/53090923/a7cc1311-d7b6-455d-8011-1d43ea6ee0a2)

in our SPA , using powerbi-client-react lib

![image](https://github.com/microsoft/powerbi-client-react/assets/53090923/4d0e71e6-31b1-4dc5-9553-44a669ce70f4)

We are not adding css to any of the classes explicitly except height and width of this below class
![image](https://github.com/microsoft/powerbi-client-react/assets/53090923/dd2da570-a043-4a36-9505-d1b30f06ca98)

Please check this issue asap, let us know if we are missing  anything

**Comment by v-MadhavC** [comment]
We Have embedded a sample report using Power BI Client React library but we are not experiencing any CSS mismatching issue when the report is rendered.

For better understanding of the issue can you please provide some additional details regarding how you are embedding your report.

Embedded report using React-wrapper in Mobile layout.
![image](https://github.com/microsoft/powerbi-client-react/assets/126773262/a389888b-3db4-4b77-bc9c-1efcdc866af0)

**Comment by xeroOrex** [comment]
Thanks @v-MadhavC for your response.

By mismatch I meant how it renders in native Power BI Mobile app and how it renders using the powerbi -client-react library in a mobile device are different. You can see the screenshot.

Here is the configuration we are using. Please let me know if you need more details. I would be happy to provide if any more info is needed.

`  const [repConfig, setConfig] = useState({
    type: "report",
    embedUrl: undefined,
    id: undefined,
    hostname: "https://app.powerbi.com",
    tokenType: models.TokenType.Embed,
    accessToken: undefined,
    settings: {
      layoutType:
        window.innerWidth > 768
          ? models.LayoutType.Custom
          : models.LayoutType.MobilePortrait,
      customLayout: {
        displayOption: models.DisplayOption.FitToWidth,
      },
      navContentPaneEnabled: false,
      panes: {
        filters: {
          expanded: false,
          visible: false,
        },
      },
    },
  });

  useEffect(() => {
    if (props.item) {
      setConfig({
        ...repConfig,
        embedUrl: props.item.embedUrl,
        accessToken: props.item.accessToken,
        id: props.item.id,
      });
    }
  }, [props.item]);`

Then using this config we are rendering the report

`    <div className="App-Report">
      <header className="App-header">
        <PowerBIEmbed
          embedConfig={repConfig}
          eventHandlers={
            new Map([
              [
                "loaded",
                function () {
                  console.log("Report loaded");
                  props.closeLoader();
                  setReportLoaded(true);
                },
              ],
              [
                "rendered",
                function () {
                  console.log("Report rendered");
                },
              ],
              [
                "error",
                function (event) {
                  console.log(event.detail);
                },
              ],
            ])
          }
          cssClassName={`Embed-container ${
            toggleHamburger == false &&
            isReportLoaded == true &&
            "hamburgerclosed"
          }`}
          getEmbeddedComponent={(embeddedReport) => {
            window.report = embeddedReport;
          }}
        />
      </header>
    </div>`

**Comment by v-MadhavC** [comment]
This is an old issue, is it still relevant?

**Comment by v-MadhavC** [comment]
We are waiting for your response. If no response is received within the next couple of weeks, the issue will be closed.

**Comment by ayeshurun** [comment]
The issue is closed since no response was received.
