### ISSUE TITLE
Change in layoutType when orientation changes gives blank power BI report

### ISSUE THREAD

**Issue by xeroOrex** [microsoft/powerbi-client-react#102]
we have a report with initial layout type as MobilePortrait like below.

`  const [repConfig, setConfig] = useState({
    type: "report",
    embedUrl: undefined,
    id: undefined,
    hostname: "https://app.powerbi.com",
    tokenType: models.TokenType.Embed,
    accessToken: undefined,
    settings: {
      layoutType:
        window.innerWidth > 768
          ? models.LayoutType.Custom
          : models.LayoutType.MobilePortrait,
      customLayout: {
        displayOption: models.DisplayOption.FitToWidth,
      },
      navContentPaneEnabled: false,
      panes: {
        filters: {
          expanded: false,
          visible: false,
        },
      },
    },
  });`

So , as anyone can see the initial setup is MobilePortrait when window's innerwidth prop is less than 768. We want to handle the screen orientation change event and change the layout to MobileLandscape.

For that we have registered orientation change event handler in our useeffect like below
`window.screen.orientation.addEventListener(
        "change",
        handleOrientationChange
      )`
in the handleOrientationChange , we try to update the layout type like below

`   const newSettings = {
              layoutType: models.LayoutType.MobileLandscape
          };
            window.report?.updateSettings(newSettings);`

But this generates an empty report. The charts , graph gets removed from the report. only blank screen is visible. change in the orientation again (from landscape to portrait) brings back the original report.

Can anyone please tell what we are missing here??!! Thanks in advanced

**Comment by v-MadhavC** [comment]
We tried implementing the code snippet provided along with some changes which resolved the issue. 
Instead of specifying the layout type condition inside the useState(), specify it inside the useEffect(). 

Please refer to the following code given below: 

```
const [sampleReportConfig, setReportConfig] = useState<models.IReportEmbedConfiguration>({ 

        type: 'report', 

        embedUrl: undefined, 

        tokenType: models.TokenType.Embed, 

        accessToken: undefined, 

        // settings: undefined, 

        settings: { 

            layoutType: models.LayoutType.MobileLandscape 

           },  

    }); 

useEffect(() => { 

        const handleOrientationChange = async () => { 

            const newLayoutType = window.innerWidth > 768 ? models.LayoutType.MobileLandscape : models.LayoutType.MobilePortrait; 

            const updatedSettings = { 
                layoutType: newLayoutType 
            }; 

            try { 
                if (report && report.updateSettings) { 
                    await report.updateSettings(updatedSettings); 
                } 
            } catch (error) { 
                console.log(error); 
            } 
        }; 

        window.addEventListener('resize', handleOrientationChange); 

         return () => { 
            window.removeEventListener('resize', handleOrientationChange); 
        }; 
    }, [report]); 
```

Please let us know if you face any issue in this.
