### ISSUE TITLE
"self is not defined" error

### ISSUE THREAD

**Issue by alexandre-codyus** [microsoft/powerbi-client-react#103]
I'm using this lib on a NextJS application.

Just updated to 13.5.3 and all pages with embed reports shows the same error below:

Unhandled Runtime Error
Error: self is not defined

Call Stack
updateDehydratedSuspenseComponent
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (16362:0)
updateSuspenseComponent
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (16058:0)
beginWork$1
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (17380:0)
beginWork
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (25702:0)
performUnitOfWork
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (24553:0)
workLoopSync
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (24269:0)
renderRootSync
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (24224:0)
performConcurrentWorkOnRoot
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (23359:0)
workLoop
node_modules\next\dist\compiled\scheduler\cjs\scheduler.development.js (261:0)
flushWork
node_modules\next\dist\compiled\scheduler\cjs\scheduler.development.js (230:0)
MessagePort.performWorkUntilDeadline
node_modules\next\dist\compiled\scheduler\cjs\scheduler.development.js (534:0)

Maybe some webpack error ?

Environment:

Windows 11 Pro
Running nextjs using "npm run dev" without containers.

**Comment by v-MadhavC** [comment]
Please refer to this GitHub issue.
["Server Error ReferenceError: self is not defined" in use the lib with typescript project · Issue #83 · microsoft/powerbi-client-react (github.com)](https://github.com/microsoft/powerbi-client-react/issues/83)
