### ISSUE TITLE
how to sync sub visuals embed with report embed?

### ISSUE THREAD

**Issue by alan9518** [microsoft/powerbi-client-react#105]
Im using the react clietn to embed a main report with several visuals, this is the config: 
```
 <PowerBIEmbed
        embedConfig={INITIAL_REPORT_CONFIG}
        eventHandlers={eventHandlersMap as any}
        cssClassName={`report-style-class ${containerHeightClass}`}
        getEmbeddedComponent={(embedObject) => {
          setReport(embedObject as Report);
        }}
      />
```

```
const INITIAL_REPORT_CONFIG: models.IReportEmbedConfiguration = {
  type: "report",
  tokenType: models.TokenType.Aad,
  slicers: [INITIAL_SLICER_DATA],
  settings: {
    layoutType: models.LayoutType.Custom,
    customLayout: {
      pageSize: {
        type: models.PageSizeType.Widescreen,
      },
      displayOption: models.DisplayOption.FitToPage,
    },
    filterPaneEnabled: false,
    persistentFiltersEnabled: false,
    personalBookmarksEnabled: true,
    navContentPaneEnabled: false,
    bars: {
      actionBar: {
        visible: false,
      },
    },
    panes: {
      bookmarks: {
        visible: false,
      },
      syncSlicers: {
        visible: true,
      },
    },
    hyperlinkClickBehavior: models.HyperlinkClickBehavior.NavigateAndRaiseEvent,
    // hyperlinkClickBehavior: models.HyperlinkClickBehavior.NavigateAndRaiseEvent,
    visualRenderedEvents: true,
  },
  // accessToken: userData.accessToken,
  id: import.meta.env.VITE_POWERBI_REPORT_ID,
};
```

and when I click in a special button I load some visuals inside a modal window using the "visual" type in the embed settings in a new component another PowerBIEmbed component. with this settings :
```
const [subVisualEmbedConfig] = useState<models.IVisualEmbedConfiguration>({
    type: "visual",
    pageName: pageName,
    visualName: visualId,
    tokenType: models.TokenType.Aad,
    // slicers: [INITIAL_SLICERS],
    settings: {
      layoutType: models.LayoutType.Custom,
      customLayout: {
        pageSize: {
          type: models.PageSizeType.Widescreen,
        },
        displayOption: models.DisplayOption.FitToWidth,
      },
      visualSettings: {
        visualHeaders: [
          {
            settings: {
              visible: false,
            },
            /* No selector is listed. The API hides the headers of all the visuals in the report. */
          },
        ],
      },
      filterPaneEnabled: false,
      persistentFiltersEnabled: false,
      personalBookmarksEnabled: true,
      navContentPaneEnabled: false,
      bars: {
        actionBar: {
          visible: false,
        },
      },
      panes: {
        bookmarks: {
          visible: false,
        },
        filters: {
          visible: false,
        },
        pageNavigation: {
          visible: false,
        },
        syncSlicers: {
          visible: true,
        },
      },
    },
    accessToken: userAuthToken,
    id: import.meta.env.VITE_POWERBI_REPORT_ID,
  });
```

  the problem here is that if a slicer or filter is applied  the main report updates the visuals inside the report correctly but the same visuals  that are in the modal window are not getting updated, and dont reflect the changes from the main report, is there any way to achieve this ?

**Comment by KotanaSai21** [comment]
It won't be possible for the visual embedded below the report should also be filtered when we apply filters to report since the report and visual are embedded in two different iframes.

However, as a workaround you can try this.
1.  Whenever filter/ slicer applied to the report, report gets rendered. 
2. When the report gets rendered, you can get the filters / slicers using the API. 
3. Compare the new filter array with the old filter array to check if the filters are changed when the report gets rendered. 
4. When the filters are applied to the report, apply the same filters to the visual below.

**Comment by alan9518** [comment]
thanks

> It won't be possible for the visual embedded below the report should also be filtered when we apply filters to report since the report and visual are embedded in two different iframes.
> 
> However, as a workaround you can try this.
> 
> 1. Whenever filter/ slicer applied to the report, report gets rendered.
> 2. When the report gets rendered, you can get the filters / slicers using the API.
> 3. Compare the new filter array with the old filter array to check if the filters are changed when the report gets rendered.
> 4. When the filters are applied to the report, apply the same filters to the visual below.

Thanks, thats what I ended up doing
