### ISSUE TITLE
How to keep embedded dashboard up-to-date?

### ISSUE THREAD

**Issue by aron51** [microsoft/powerbi-client-react#106]
I have an application that allows users to embed a Power BI dashboard. I've noticed that some changes, such as moving tiles, are automatically reflected in the embedded dashboard, but others, like removing a tile, are not. Is there a method to ensure the embedded dashboard stays in sync with the Power BI version, including all changes?

Thank you!

**Comment by KotanaSai21** [comment]
Use `reload()` API and it reloads the embed using the existing configuration.  

Refer to [powerbi-client-dashboard-reload](https://learn.microsoft.com/javascript/api/powerbi/powerbi-client/dashboard.dashboard#powerbi-client-dashboard-dashboard-reload).

**Comment by aron51** [comment]
Thanks. Is there any documentation somewhere about what is synced automatically, without calling reload? Like the thing I mentioned, moving around tiles are reflected without a reload

**Comment by v-MadhavC** [comment]
Changes like moving tiles usually synced automatically in the embedded dashboard without needing to call reload(). However, more significant updates, such as adding or removing tiles, usually require calling the reload() API to reflect those updates in the embedded dashboard. As for the specific details—there's no documentation that lists which changes sync automatically and which require a reload.
