### ISSUE TITLE
advanced date filter not updating visuals

### ISSUE THREAD

**Issue by alan9518** [microsoft/powerbi-client-react#107]
Im trying to update some visuals filters based on the value of some slicers, 

im using `visual.updateFilters(models.FiltersOperations.ReplaceAll, newFilters)` I'm iterating over the slices and retrieve the slicer state using `getSlicerContextByName` function, which works fine for sllicers that use basic filters, but when I try to do the same with a date selector slicer it wont work i can extract the date filter but it does not do anything with that.

any idea on what can be done ?

```
{
    "filters": [
        {
            "$schema": "http://powerbi.com/product/schema#advanced",
            "target": {
                "table": "Calendar",
                "column": "Fecha"
            },
            "filterType": 0,
            "logicalOperator": "And",
            "conditions": [
                {
                    "operator": "GreaterThanOrEqual",
                    "value": "2023-12-01T06:00:00.000Z"
                },
                {
                    "operator": "LessThan",
                    "value": "2024-02-26T06:00:00.000Z"
                }
            ]
        }
    ],
    "targets": [
        {
            "table": "Calendar",
            "column": "Fecha"
        }
    ]
}
```

here is the list of filters that are being updated using `visual.updateFilters(models.FiltersOperations.ReplaceAll, newFilters)` 

![image](https://github.com/microsoft/powerbi-client-react/assets/13058957/ed53ef0b-52f0-40cc-aca8-07de74738d2e)

**Comment by KotanaSai21** [comment]
We followed the steps that were mentioned and were able to reproduce the issue. 

Using `visual.updateFilters(models.FiltersOperations.ReplaceAll, newFilters)` will filter the slicer visual only and not the entire report.  You can use [Set Slicer State](https://learn.microsoft.com/en-us/javascript/api/overview/powerbi/control-report-slicers#set-slicer-state) for the report to get Sliced along with the slicer visual. 

Refer [Use slicers when embedding a report in Power BI embedded analytics | Microsoft Learn](https://learn.microsoft.com/en-us/javascript/api/overview/powerbi/control-report-slicers#range-slicer) for more information.

You can play with the API here [Power BI Playground - Developer Sandbox](https://playground.powerbi.com/en-us/dev-sandbox)
