### ISSUE TITLE
Changes in supplied filters are not reflected in PowerBIEmbed

### ISSUE THREAD

**Issue by danidiaz** [microsoft/powerbi-client-react#11]
When, inside the `embedConfig` prop, `embedUrl`  remains the same but the [array of filters](https://github.com/Microsoft/PowerBI-JavaScript/wiki/Filters) changes, this is not reflected in the `PowerBIEmbed` component, which keeps showing the old filters.

**Comment by anant-k-singh** [comment]
Updating the `filters` property of `embedConfig` prop does not apply the new filters as of now.
