### ISSUE TITLE
PowerBi embeded iframe have vertical scroll bar.

### ISSUE THREAD

**Issue by jay-git-dev** [microsoft/powerbi-client-react#118]
When embeding the report of power bi, the iframe has the vertical scroll bar even if enough height on the web page. Because of this, in the report section, we have a vertical scroll bar of power bi and the default web scroll bar.

**Comment by v-MadhavC** [comment]
We tested this by embedding a report but did not get a scroll bar. Could you please provide more details to help us reproduce the issue?

We have attached a screenshot of our embedded report, which shows no scroll bar.
![image](https://github.com/user-attachments/assets/444738db-29f3-4675-8884-c2cec235b842)

**Comment by v-MadhavC** [comment]
We are waiting for your response. If no response is received within the next couple of weeks, the issue will be closed.
