### ISSUE TITLE
Infinite loop in embedded frame

### ISSUE THREAD

**Issue by JANA-itsaishvili** [microsoft/powerbi-client-react#119]
We recently ran into an issue embedding PowerBI in our react app where the iframe goes into an infinite loop loading the `PBI-logo.947f878993d21960993f.svg` resource.

This request succeeds, but the iframe keeps requesting it indefinitely.

The only issue I can point to right now, is the `subscribe` endpoint is either cancelled or pending, and that could be triggering the internal state incorrectly: `https://wabi-canada-central-redirect.analysis.windows.net/powerbi/refresh/subscribe`

The initiator is `https://content.powerapps.com/resource/powerbiwfe/scripts/reportembed.externals.bundle.min.f9dbf5939d5b80fe9297.js` (the exact url is obviously not importat).

The gist of the issue is even if the fault is somewhere on our end, the package should not spin up an infinite loop. The package should either wait for the `subscribe` call to complete, or throw an error and return an error state. We currently have no, or minimal control as far as I'm aware, of mitigating this issue.

Here's two fragments of the network logs:
![image](https://github.com/user-attachments/assets/2278e107-114d-48a9-9b96-f2eea596828f)
![image](https://github.com/user-attachments/assets/e3788f5f-759c-4257-8576-ce530cd55389)

**Comment by JANA-itsaishvili** [comment]
**update**

**Comment by v-MadhavC** [comment]
Thank you for reporting this issue. We will reproduce it in our environment and will update you on our findings within the next few weeks.

**Comment by v-MadhavC** [comment]
We tested this scenario in our environment, and in our case, the call to the PBI logo image is made only once, even with the cache disabled.

![image](https://github.com/user-attachments/assets/cb207105-4a0d-4441-b164-581bf1f6726d)

Could you please provide more details to reproduce the issue.

**Comment by v-MadhavC** [comment]
We tested this on a `trial version` with both caching enabled and disabled, and the call to the `PBI-logo.svg` resource occurs only once in our environment. This suggests the issue might be related to your application setup. Could you kindly review your code for any unintended re-renders or logic that might be causing repeated requests.

![Image](https://github.com/user-attachments/assets/03a92e91-43d5-4266-a399-058c6d34cb41)

**Comment by v-MadhavC** [comment]
We are waiting for your response. If no response is received within the next couple of weeks, the issue
will be closed.

**Comment by JANA-itsaishvili** [comment]
It definitely was related to a specific setup, but if you `✅ Disable Cache`, you still see only a single request?

**Comment by lagwalsahil21821** [comment]
The PBI-logo.svg resource is loaded only once during the report embedding process, even with `Disable Cache` enabled.

![Image](https://github.com/user-attachments/assets/fad3815b-d599-4d6c-a185-c9e4a96867ce)

Please ensure you’re using the latest version of the powerbi-client-react package. You can find the latest version here: [powerbi-client-react - npm (v1.4.0)](https://www.npmjs.com/package/powerbi-client-react/v/1.4.0)
