### ISSUE TITLE
Not able to hide visualization pane in edit mode

### ISSUE THREAD

**Issue by GhagarePooja711** [microsoft/powerbi-client-react#121]
When we embed the report in edit mode, we were not able to hide the visualization pane. 

![image](https://github.com/user-attachments/assets/dea55523-d544-4def-8fee-72d870b00ca3)

In the Edit mode, we were able to hide the filter, pageNavigation panes but not the visualization pane.
 
From the doc [Configure embedded report settings | Microsoft Learn](https://learn.microsoft.com/en-us/javascript/api/overview/powerbi/configure-report-settings) it says that both the visible and expanded property supported for the visualization pane, but the visible property is not working.

**Comment by v-MadhavC** [comment]
Hiding the visualization pane in edit mode is not supported. In Power BI Service, the visualization pane cannot be hidden in edit mode. To maintain consistency and a similar user experience, the visualization pane cannot be hidden.
