### ISSUE TITLE
Unable to get filter state when "rendered" event triggered

### ISSUE THREAD

**Issue by Mingyang-Li** [microsoft/powerbi-client-react#125]
## What I'm looking to achieve:
I'm building a feature that enables users to export either a single page or the entire report with the exact same views/filters from an embedded PowerBI report from my React app. 

Technical flow:
1. Frontend renders PBI report
2. User changes the report view by applying a dropdown selection or applying a filter from the filter panel
3. Report renders the new report view
4. User clicks a button to export the report with filters they've just applied
5. **This is the part I haven't yet figured out**: Frontend gets the right **filtering string** to pass to this endpoint from PowerBI REST API: `POST https://api.powerbi.com/v1.0/myorg/groups/{{WORKSPACE_ID}}/reports/{{REPORT_ID}}/ExportTo`, docs are here: https://learn.microsoft.com/en-us/rest/api/power-bi/reports/export-to-file. 
6. React app passes the input to my own backend
7. My backend calls `POST https://api.powerbi.com/v1.0/myorg/groups/{{WORKSPACE_ID}}/reports/{{REPORT_ID}}/ExportTo` to initiate the export job
8. My frontend starts doing long polling to the backend checking if the export job has been completed
9. Once completed, the frontend makes another request calling this endpoint to get the exported report: `GET https://api.powerbi.com/v1.0/myorg/groups/{{WORKSPACE_ID}}/reports/{{REPORT_ID}}` - https://learn.microsoft.com/en-us/rest/api/power-bi/reports/get-report

## Question
In an embedded report, how do i get the right value(s) for every change in report filters, so that I can pass it to `POST https://api.powerbi.com/v1.0/myorg/groups/{{WORKSPACE_ID}}/reports/{{REPORT_ID}}/ExportTo` which will trigger an export of the report that has the exact same filters I applied on the frontend of my app?

I tried using every single value from the event triggered within `<PowerBIEmbed />` event handlers as the `state` value for the post request body for `POST https://api.powerbi.com/v1.0/myorg/groups/{{WORKSPACE_ID}}/reports/{{REPORT_ID}}/ExportTo` 
```json
{
  "powerBIReportConfiguration": {
      "reportLevelFilters": [
         {
            "filter": "STATE_FROM_EMBEDDED_REPORT"
         }
      ]
  }
}
```
, but none of it worked. I'm still unable to export reports using the exact same filters I've applied in the embedded app.

Where would you start for achieving this type of feature?

**Comment by v-MadhavC** [comment]
We're closing GitHub issues on 01/01/2025.



**Please continue to share your feedback and get support through these channels:**



- **Feature Requests:** Submit your ideas and suggestions to the [Fabric Ideas Portal](https://ideas.fabric.microsoft.com/), where you can also vote on ideas from other developers.



- **Bug Reports and Technical Assistance:** Visit the [Fabric Developer Community Forum](https://community.fabric.microsoft.com/t5/Developer/bd-p/Developer). Our team and community experts are ready to assist you.



- **Additional Support:** Contact your account manager or reach out to the [Fabric Support Team](https://support.fabric.microsoft.com/en-us/support/).



We highly value your contributions and look forward to collaborating with you to enhance our offerings based on your feedback.



Thank you,

**The Power BI Embedded Team**
