### ISSUE TITLE
Issue running demo

### ISSUE THREAD

**Issue by karlrez** [microsoft/powerbi-client-react#126]
I am running this repo without any code changes. After clicking the "Embed Report" I get this error:

![Image](https://github.com/user-attachments/assets/94020cfc-810b-4ab8-9605-f3ec8ed3acd9)

is there a workaround for this?

**Comment by v-MadhavC** [comment]
We're closing GitHub issues on 01/01/2025.

Please continue to share your feedback and get support through these channels:

- **Feature Requests**: Submit your ideas and suggestions to the [Fabric Ideas Portal](https://ideas.fabric.microsoft.com/), where you can also vote on ideas from other developers.

- **Bug Reports and Technical Assistance**: Visit the [Fabric Developer Community Forum](https://community.fabric.microsoft.com/t5/Developer/bd-p/Developer). Our team and community experts are ready to assist you.
 
- **Additional Support**: Contact your account manager or reach out to the [Fabric Support Team](https://support.fabric.microsoft.com/en-us/support/).

We highly value your contributions and look forward to collaborating with you to enhance our offerings based on your feedback.

Thank you,

**The Power BI Embedded Team**
