### ISSUE TITLE
PowerBI reports don't render on Microsoft Edge 44

### ISSUE THREAD

**Issue by Nadeeshyama** [microsoft/powerbi-client-react#13]
I get the message `Power BI SDK is trying to post /report/load before iframe is ready.` in Edge console. Report view only display spinning wheels. The report never loads. My Edge version is 44.18362.449.0.

Implementation different to demo app: I make the API call in a React useEffect hook and update PowerBIEmbed embedConfig.

This works fine in Chrome.

**Comment by anant-k-singh** [comment]
Can you provide repro steps?

**Comment by Nadeeshyama** [comment]
We have re-written our app with CRA. The reports work on Legacy Edge as expected. However the above error is still thrown in browser console.
