### ISSUE TITLE
Localization update

### ISSUE THREAD

**Issue by jmetterrothan** [microsoft/powerbi-client-react#14]
Hello,

I'm trying to dynamically change the locale of the embed configuration, I was wondering if it was even possible using for instance the `updateSettings` method of a report object? 
It only works currently after the first initialization of the component. 

The properties I'm trying to change:
```javascript
{
  ...
  settings : {
    localeSettings: {
      language: "en",
      formatLocale: "en-GB"
    }
  }
}
```

Thanks!

**Comment by anant-k-singh** [comment]
Localization settings cannot be updated once the powerbi report is loaded. 
[Docs](https://github.com/microsoft/PowerBI-JavaScript/wiki/Bootstrap-For-Better-Performance#limitations)

You need to provide localization settings initially when you bootstrap/embed the report
