### ISSUE TITLE
Available filtersApplied event does not trigger an event 

### ISSUE THREAD

**Issue by nirjhar18** [microsoft/powerbi-client-react#16]
You can make changes to the report from the filter pane provided in the powerbi component but once you hit apply, no event is triggered. I can see filtersApplied event being available but it does not do anything

**Comment by anant-k-singh** [comment]
`filtersApplied` event is not triggered for filters applied via filter pane in UI

You can use `rendered` event as it is always triggered when a filter is applied

**Comment by nirjhar18** [comment]
Rendered event is called every time even for other events, there is no distinction of what event is being called. It will be better to have a distinction between the events rather than just one rendered event
