### ISSUE TITLE
Available saveAsTriggered event does not trigger an event

### ISSUE THREAD

**Issue by nirjhar18** [microsoft/powerbi-client-react#17]
There are multiple allowed events(saveAsTriggered ) in the following github repositories on which this React Library is based on. These events should be implemented so they can be used as available.

https://github.com/microsoft/PowerBI-JavaScript/blob/master/src/embed.ts#L124

https://github.com/microsoft/PowerBI-JavaScript/blob/master/src/report.ts#L34

**Comment by anant-k-singh** [comment]
`saveAsTriggered` event is no longer triggered. Instead use the `saved` event as it is triggered for both type of save events.

The event details you get in handler of `saved` event will contain the flag `saveAs: true`.
