### ISSUE TITLE
Dynamic binding not working

### ISSUE THREAD

**Issue by acraftydev** [microsoft/powerbi-client-react#18]
I am trying to dynamically bind my report to a different dataset at runtime. I correctly create an embed token with the correct permissions but no matter what value i put in the datasetId attribute on the embedConfig it always uses the default dataset for the report.

Looking at the underlying javascript api (https://github.com/microsoft/PowerBI-JavaScript/wiki/Dynamic-Binding) it looks like embedConfig is not correctly mapped to the '  datasetBinding: {
		datasetId: "xx", 
	}'
stucture on the config passed through.

thanks

**Comment by acraftydev** [comment]
Worked around the issue by setting correct property on IEmbedConfiguration and using ts-ignore to allow property to be passed through

                    embedConfig={{
                        type: 'report',
                        id: "xxxx",
                        embedUrl: "adsasdasd",
                        accessToken:"asdsad",
                        tokenType: models.TokenType.Embed,
                        *@ts-ignore
                        datasetBinding: {
                            datasetId: "datasetid",
                        },
                        settings: {
                            panes: {
                                pageNavigation: {
                                    visible: false
                                },
                                filters: {
                                    expanded: false
                                }
                            }
                        }
                    }}

**Comment by anant-k-singh** [comment]
Will be fixed soon

**Comment by anant-k-singh** [comment]
This is fixed in powerbi-client v2.15.1
Cleaning the _node_modules_ and reinstalling the _powerbi-client-react_ package should be enough
