### ISSUE TITLE
How to get access token?

### ISSUE THREAD

**Issue by rafiandria23** [microsoft/powerbi-client-react#20]

**Comment by nirjhar18** [comment]
If you are looking to get an access token for Power BI. Please use the following API

POST /v1.0/myorg/GenerateToken HTTP/1.1

Host: api.powerbi.com

Authorization: Bearer token

Content-Type: application/json

{
  "datasets": [
    {
      "id": "123"
    }
  ],
  "reports": [
    {
      "allowEdit": true,
      "id": "Report ID 456"
    }
  ]
}

**Comment by rafiandria23** [comment]
Thanks, @nirjhar18 :tada:
