### ISSUE TITLE
Calls to Refresh time out

### ISSUE THREAD

**Issue by ChrisPerrinIS** [microsoft/powerbi-client-react#23]
It looks like calls to refresh our Power BI report take about 2 minutes.  As such, they seem to time out/cancel before they ever finish running.

In turn, it looks like our token is not refreshing and the new access token is not being accepted.  The end result is we see a lot of Canceled calls in the network tab and eventually we see the X's and errors fill the log.

**Comment by anant-k-singh** [comment]
If you update the embed config in props with the new access token, new access token will be set in the report, and report will continue to work fine.
But, if your new token is set **after** the current token has expired, in that case you'll have to call the `report.reload()` manually after providing the new access token

You can refer this [example from powerbi-client SDK](https://github.com/microsoft/PowerBI-JavaScript/wiki/Refresh-token-using-JavaScript-SDK-example).
