### ISSUE TITLE
Any plans for react-native?

### ISSUE THREAD

**Issue by MayankDargan** [microsoft/powerbi-client-react#24]
I couldn't find any library for react-native integrating powerbi reports. Are there any plans for something for power bi with react-native?

**Comment by bwoodlt** [comment]
+1

**Comment by ColinKrist** [comment]
haven't used react-native in a fair bit, but wouldn't this be accomplished with a WebView?

**Comment by KotanaSai21** [comment]
Currently not supported for react-native. Keeping this issue Open to collect votes.

**Comment by v-MadhavC** [comment]
Thank you for reporting this issue. This is a feature request, please add it in the following link where we can collect votes: https://ideas.fabric.microsoft.com . If the feature is already there, you can add a vote.
