### ISSUE TITLE
Power BI Report in SharePoint Team Site

### ISSUE THREAD

**Issue by gselvag** [microsoft/powerbi-client-react#26]
Thank you for your work with this Power BI client react. We want implement a Power BI dashboard, during provisioning Team Site on SharePoint. Our business case is that we need to include/create Power BI report (web part or iFrame). How to add the report on a Client Site Page during provisioning the site template. 

The challenge is to include Power BI reports, that incorporate SharePoint lists and/or excel files - add Power BI reports with relative URL provisioned site as data source for the reports.

Would appreciate tips if this is possible, and how we're able to do this!

**Comment by may-hartov** [comment]
Issue is not related to powerbi-client-react component, please visit [Power BI Support page](https://powerbi.microsoft.com/en-us/support/). Closing as this is not relevant for this github page context,
