### ISSUE TITLE
Set filter configuration for report

### ISSUE THREAD

**Issue by NazarKryvyy** [microsoft/powerbi-client-react#29]
Hi, my question is about configuring filters for the embedded reports.

**Current behavior** 

The type of property filter in ```IEmbedConfiguration``` is 
```filters?: models.IFilter[];```,  and  ```IFilter``` itself is 

```typescript 
export interface IFilter {
    $schema: string;
    target: IFilterGeneralTarget;
    filterType: FilterType;
    displaySettings?: IFilterDisplaySettings;
}
```
For configuring any report's filter this set of property is not enough.

**Expected behavior**

 For example for the basic type of filter, the set of properties is 

```typescript
export interface IBasicFilter extends IFilter {
    operator: BasicFilterOperators;
    values: (string | number | boolean)[];
    requireSingleSelection?: boolean;
}
```
So I would expect to have  ```IReportLoadConfiguration```  where ```filters?: ReportLevelFilters[];``` and 

```ReportLevelFilters = IBasicFilter | IBasicFilterWithKeys | IAdvancedFilter | IRelativeDateFilter | ITupleFilter | IRelativeTimeFilter```.

Can you advise me on how to set filters properly for reports?

**Comment by harishv6665** [comment]
Even I am scratching my head around it to apply filters. Nothing worked so far.
Can someone confirm if it is supported or not??

**Comment by nirjhar18** [comment]
There is a function "setFilters" that you can use on each visual on a report to apply filters. To see how that works, you can look into

https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html#

You can go into Sample Report -> Interact and you can find an example for setting filters.

**Comment by anant-k-singh** [comment]
I think setting the filters via props would work fine (in JS), the issue is with TS type of `IEmbedConfiguration.filters`.
Short term workaround would be to just pass filters of type `models.ReportLevelFilters[]` and add `// @ts-ignore` in the above line

**Comment by harishv6665** [comment]
> There is a function "setFilters" that you can use on each visual on a report to apply filters. To see how that works, you can look into

Thanks for the reply. Is there any example of how to set filters using powerbi-client-react???
Any simple example would be really helpful.

**Comment by harishv6665** [comment]
> I think setting the filters via props would work fine (in JS), the issue is with TS type of `IEmbedConfiguration.filters`.
> Short term workaround would be to just pass filters of type `models.ReportLevelFilters[]` and add `// @ts-ignore` in the above line

@anant-k-singh I tried and got the below error

Code:
```
<PowerBIEmbed
	embedConfig={{
		...embedConfig,
		type: "report",
		tokenType: models.TokenType.Embed,
		filters: [{
				$schema: "http://powerbi.com/product/schema#basic",
				target: {
				table: "TABLE_NAME",
				column: "COLUMN_NAME"
				},
				// @ts-ignore 
				operator: "Is",
				values: "XYZ"
			}]
	}}
/>
```
![image](https://user-images.githubusercontent.com/7059258/103799084-9c134580-5070-11eb-92b0-7d06fc12ca33.png)

**Comment by anant-k-singh** [comment]
@harishv6665 
1. If you are using TypeScript, then you can put @ts-ignore like this:
```jsx
<PowerBIEmbed
	embedConfig={{
		...embedConfig,
		type: "report",
		tokenType: models.TokenType.Embed,
                // @ts-ignore 
		filters: [{
				$schema: "http://powerbi.com/product/schema#basic",
				target: {
				table: "TABLE_NAME",
				column: "COLUMN_NAME"
				},
				operator: "Is",
				values: "XYZ"
			}]
	}}
/>
```
1. Check out the docs for [Constructing Filters](https://github.com/Microsoft/PowerBI-JavaScript/wiki/Filters#constructing-filters) to verify your filter array.

**Comment by NazarKryvyy** [comment]
@harishv6665
There are 3 levels of applying filters: Report, Page, Visual. Most time you would work with the visuals. 

To get visual:

1. Find an active page.
2. Request all visuals on this page
3. Search for the visual you need.

Then you can set filter and slicerState for visual. Filters are for filtering data in your visual, e.g. you have a year picker and it has 3 available yers to choose 2020, 2019, and 2018. If a filter with value 2020 is set for year picker visual, "2020" would be the only option that remains in it. If you want just to choose a value in it use setSlicerState(filterConfig) instead setFilter(filterConfig).

After receiving the expected visual, request it slicer state with ```await visual?.getSlicerState()``` and check a `target` property to get the propper table name. In my case, it differs from what I see in UI. Then you can properly configure a filter for your slicer.

One more tip, you can also manually configure any visual then request its slicerState and check what filter configuration is using in this visual.

Use this   [wiki](https://github.com/microsoft/PowerBI-JavaScript/wiki) for more info.

```tsx
const monthFilterConfig = {
    $schema: "http://powerbi.com/product/schema#basic",
    filterType: 1,
    target: {
        table: "TableName", // table name you can get from visual entity
        column: "Month"
    },
    operator: "In", // FYI "Is" is not acceptable, check BasicFilterOperators
    values: [momet().format("MMMM")],
    requireSingleSelection: false
}

const PowerBIReport = () => {
  const [report, setReport] = useState<Report>();

  const setFilterForVisual= async () => {
        const pages = await report?.getPages();
        const activePage = pages?.filter(function(page) {
            return page.isActive;
        })[0];
        if (activePage) {
            const visuals = await activePage.getVisuals();
            const monthVisual = visuals.find((item)=>visual.title === "Month")
            await monthVisual.setSlicerState({ filters: [monthFilter] });            
        }
    };
  
  return (
    <PowerBIEmbed
         embedConfig={sampleReportConfig}
         eventHandlers={eventHandlersMap}
         getEmbeddedComponent={(embedObject) => {
           setReport(embedObject as Report);
         }}
     />
  )
}
```

**Comment by anant-k-singh** [comment]
With v1.3.1, you can use the new `IReportEmbedConfiguration` for embedding reports, it has the property `filters?: ReportLevelFilters[];`.

**Comment by Amol-jagdale** [comment]
is it fine if we use https instead of htttp in filter($schema)

**Comment by WeslleyBorges** [comment]
> @harishv6665
> 
> 1. If you are using TypeScript, then you can put @ts-ignore like this:
> 
> ```js
> <PowerBIEmbed
> 	embedConfig={{
> 		...embedConfig,
> 		type: "report",
> 		tokenType: models.TokenType.Embed,
>                 // @ts-ignore 
> 		filters: [{
> 				$schema: "http://powerbi.com/product/schema#basic",
> 				target: {
> 				table: "TABLE_NAME",
> 				column: "COLUMN_NAME"
> 				},
> 				operator: "Is",
> 				values: "XYZ"
> 			}]
> 	}}
> />
> ```
> 
> 1. Check out the docs for [Constructing Filters](https://github.com/Microsoft/PowerBI-JavaScript/wiki/Filters#constructing-filters) to verify your filter array.

You are just a god, bro. Thank you so much.

**Comment by Sudarshanchandrasekar** [comment]
This might help for some people. 
In typescript, the setFilters() method does not work during on load of the PowerBI pages in the react app. However, if you simulate a button click event for applying filters after the PowerBI page is loaded, it is working for me. 

The powerbi-client npm package needs an external click event to apply the filter conditions after the PowerBI page is loaded in typescript. 

Hope someone will find this helpful. Thanks.
