### ISSUE TITLE
Power BI React Client is not React at all?

### ISSUE THREAD

**Issue by Tzvetelin88** [microsoft/powerbi-client-react#31]
Hello,
Is this a real React Client for Power BI? 
It seems this "library" is just doing iframe for the hole BI page?
So there is no real React integration with BI product, it's just Iframe or I'm wrong?

![image](https://user-images.githubusercontent.com/9692941/102509912-c4baa780-408f-11eb-8dd4-9f26c7b80c6d.png)

**Comment by anant-k-singh** [comment]
This library wraps the core [powerbi-client](https://github.com/microsoft/powerbi-javascript) into a React component, to make it easier for developers to use Power BI Embedded capabilities in a React application.
Yes, the [powerbi-client](https://github.com/microsoft/powerbi-javascript) library embeds into an iframe.

**Comment by Tzvetelin88** [comment]
On the road map, are there plans for React component integration with PowerBi, so each component from BI can be represent in React - in a customizable, responsive and styled way? I know Microsoft loves React and many of Microsoft applications are build on React.
It will be very nice to have this integration. Many companies are using PowerBI and Databricks REST API to integrate with their own applications, but currently PowerBI integration is not in the best shape. Thanks!
