### ISSUE TITLE
How to integrate the (Create mode) report feature with this package 

### ISSUE THREAD

**Issue by kirti3** [microsoft/powerbi-client-react#34]
Hi Team 

I need to implement the create mode report feature but i am not able to find the way in the configuration to implement it
Could you please guide and provide code sample config for create 

Thanks

**Comment by nirjhar18** [comment]
You can look into embedding the report in edit mode. You should get a save option once it is in edit mode. I have not tried the create mode. In the embed config, where you provide the mode you can just change it to Edit

**Comment by kirti3** [comment]
Hi Nirjhar 

Thank you the reply and helping

I tried it with edit it's working as per edit  but in different way but i want to implement the only **Create mode** so that user can create new report 

Below is the example mentioned in playground for create mode
  https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html#

Ss of create mode 
<img width="1626" alt="Screen Shot 2021-02-24 at 8 43 19 PM" src="https://user-images.githubusercontent.com/68562621/109090441-f4fe7200-76e0-11eb-8006-ea300ec6ff30.png">


As per code - **For create mode they are using** 
var report = powerbi.**createReport**(embedContainer, embedCreateConfiguration); instead of **embed** 

I am able to execute all almost all examples mentioned in playground with this package but not able to find a way 
1. **Create mode 
2. How to share a report** 

And even i checked the implementation of  https://github.com/microsoft/powerbi-client-react , only embed is implemented and for create mode i feel we need to do something different.

**Comment by nirjhar18** [comment]
I am not 100% what is different in the create mode but you can embed an empty report in edit mode which would just be similar to create a report.

**Comment by anant-k-singh** [comment]
Report is created using the **createReport** API of [Power BI JS SDK](https://github.com/microsoft/PowerBI-JavaScript).
The **createReport** API is not supported in this React library as of now.
