### ISSUE TITLE
"refreshNotAllowed"

### ISSUE THREAD

**Issue by ArasBazyan** [microsoft/powerbi-client-react#35]
Hi,

When trying to update reports for different RLS users, this error messaged is returned:
```
detailedMessage: "Report refresh limit of 1 request(s) every 15 seconds reached. Please try again later."
message: "refreshNotAllowed"
```

Context:
We use 
```
report?.refresh();
```
To refresh the reports for different users. 
Receiving new config and updating the config didn't update the content of the reports, that's why after setting the new config we use `refresh()`, and that's when we receive the error when trying to update the report for different RLS users under 15 seconds. 

```
 updateReportConfig({
        ...localConfig,
        embedUrl: reportConfig?.embedReport[0].embedUrl,
        accessToken: reportConfig?.embedToken.token
      });
```

Has anyone faced the same issue? Is there a better way to apply new config and refresh the content? ( report.relaod() didn't work either).

**Comment by KotanaSai21** [comment]
We need more details and perhaps traces to investigate. Please Contact [PowerBI support](https://powerbi.microsoft.com/en-us/support/)
