### ISSUE TITLE
DemoApp sample report throws error

### ISSUE THREAD

**Issue by Macs89** [microsoft/powerbi-client-react#38]
The demo app sampleReport throws an error:

Response status code does not indicate success: 401 (Unauthorized).
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: Response status code does not indicate success: 401 (Unauthorized)
AdalServiceException: AADSTS7000222: The provided client secret keys are expired. Visit the Azure Portal to create new keys for your app, or consider using certificate credentials for added security: https://docs.microsoft.com/azure/active-directory/develop/active-directory-certificate-credentials
Trace ID: db6f3573-78bf-4fc8-8aca-0d2932597600
Correlation ID: 6c707ff9-51eb-4485-a592-e11045e976a9

![image](https://user-images.githubusercontent.com/73954165/112467405-4d1fa700-8d67-11eb-8aa4-03b90521dcdd.png)

**Comment by RobGriggs** [comment]
Same issue: 
Chrome Inspector for report XHR Get request: 
![image](https://user-images.githubusercontent.com/2215578/112522141-45620180-8d6b-11eb-8380-39294a9a1c55.png)

**Comment by borishere** [comment]
Please fix it.

**Comment by KotanaSai21** [comment]
This issue is fixed.
