### ISSUE TITLE
How to print a report

### ISSUE THREAD

**Issue by sunilsharma2214** [microsoft/powerbi-client-react#42]
I saw in powerbi-client

var element = document.getElementById('#myReport');
var report = powerbi.get(element);

report.print()
  .catch(error => { ... });

do we have same in react-powerbi-client? like 
 <PowerBIEmbed
      embedConfig={reportConfig}
      eventHandlers={
        new Map([
          ['loaded', function () {}],
          ['rendered', function () {}],
          ['error', function (event) {}],
        ])
      }
      cssClassName={'powerbi-embeded-style'}
      getEmbeddedComponent = { (embeddedReport) => {
       
        embeddedReport.print();
      }}
    />

**Comment by sunilsharma2214** [comment]
I think, I got

embeddedReport.service.get(embeddedReport.element).print();

**Comment by KotanaSai21** [comment]
In the demo we can access the report using the report object.

```
if (!report) {
			setDisplayMessageAndConsole('Report not available');
			return;
		}
		try {
			await report.print();
		}
		catch (errors) {
			console.log(errors);
		}
```

References:
[powerbi-embedding-basic-interactions](https://learn.microsoft.com/javascript/api/overview/powerbi/embedding-basic-interactions)
