### ISSUE TITLE
PowerBIEmbed does not support paginated report

### ISSUE THREAD

**Issue by AlliceSmash** [microsoft/powerbi-client-react#43]
Hello, is it possible to create a new component that embed paginated report? Based on the type definition, paginated report seems to use IPaginatedReportLoadConfiguration which is not part of supported type in PowerBIEmbed. If that is possible, can you let me know how to se it up? In addition the model IPaginatedReportLoadConfiguration is different from https://docs.microsoft.com/en-us/javascript/api/overview/powerbi/embed-paginated-report which includes type and embedUrl.  Is that by design or the document is outdated?

**Comment by KotanaSai21** [comment]
Thank you for pointing this out. We have updated the package and now you can Embed a paginated report using [IPaginatedReportConfiguration](https://learn.microsoft.com/javascript/api/powerbi/powerbi-models/ipaginatedreportloadconfiguration) interface.

Feel free to reach out for any other queries.
