### ISSUE TITLE
Report.refresh() missing from readme?

### ISSUE THREAD

**Issue by tappin-kr** [microsoft/powerbi-client-react#44]
Looking through the docs in this repo, there is no mention of report.refresh() https://github.com/microsoft/PowerBI-JavaScript/blob/master/src/report.ts#L515

For our app, doing a report.reload() is only grabbing the /modelsAndExploration endpoint, which was only updating the visuals on the report.

Doing a report.refresh() hits the actual querydata endpoint which is updating the report with the latest report data.

FYI for anyone that is looking into why a report.reload() is not updating the data in their report.

**Comment by RePinheiro** [comment]
I have the same problem

**Comment by KotanaSai21** [comment]
`report.reload()` method reload the embed and reset the current filters and user interactions and return to original embed configuration.

`report.refresh()` refreshes the underlying data of an embedded report without resetting the filters or user interactions. It works only in Direct Query mode.

Both the Apis are supported in the package.

Please find the references here 
[General operations in a Power BI embedded analytics application | Microsoft Learn](https://learn.microsoft.com/en-us/javascript/api/overview/powerbi/embedding-basic-interactions#reload-a-component)
