### ISSUE TITLE
StringValueTooLong on Embedded Report

### ISSUE THREAD

**Issue by boyanhtrai** [microsoft/powerbi-client-react#46]
![image](https://user-images.githubusercontent.com/29662022/119635955-5ea42e80-be3e-11eb-80a6-a765d3871fca.png)

I saw this bug and I found some information about it.
https://community.powerbi.com/t5/Developer/AI-StringValueTooLong-on-Embedded-Report/m-p/876516

This bug will remove all filter from FE.
Who can you support me about it? It is a bug? Thank you

**Comment by v-MadhavC** [comment]
Thank you for reporting this issue. We closed the issue because it's old.
