### ISSUE TITLE
Requirement for specific region settings

### ISSUE THREAD

**Issue by eglavin** [microsoft/powerbi-client-react#48]
Hi just wondering if there is any method to force the Language/Region that will be used for the date pickers? 

Right now the way the Power Bi viewer is using the browser to choose the date/region settings is causing an issue for me where my "English (Ireland)" (Windows 10 PC) is showing an "English (United States)" (Somehow chosen by MS Edge...) format? The way I'm dealing with locale and i18n for the rest of the app is by using an value from the users data, which makes Power Bi an outlier right now where it pulls its locale info from the users browser, Is there any way to change this?

**Comment by LevinGar** [comment]
That is defined in the pbix itself, when a new file is being created the region and language configuration is set in its creation, the visual components such as the date pickers take the defined region configuration that the pbix have in that moment as other components of the report. These configurations are kept even when the pbix is updated. I have seen some ways to deal with the problem: Premium has its own features to deal with region configuration. Another way without acquiring premium is to make other reports sharing the same dataset was created in the base report in order or not duplicating information and hitting the performance. Based on the client configuration on the client-side you can call the report with the corresponding region configuration.
