### ISSUE TITLE
PowerBIEmbed component is displaying the report with incorrect data

### ISSUE THREAD

**Issue by shivaprasad-manjunath** [microsoft/powerbi-client-react#49]
We are using PowerBI for report generation and we are using the PowerBIEmbed component to display those reports in our application. In our react application,

1. we have different tabs based on different types of reports, and
2. we have a set of filters exposed to users

So, based on the tab (i.e., report type) and filters selected we populate 'embedConfig'. We pass this config to the PowerBIEmbed component. Based on that appropriate reports are fetched and displayed in our application.

**Issue**: Under a particular tab modifying the filter values fetches the reports with correct data, whereas for selected filter values changing the tab is fetching the report with incorrect data.

_Onservation_: Upon debugging we observed that /querydata API calls internally called by powerbi-client-react are invoked with the right queries. But the data in the report fetched is incorrect.

May I know if we are doing something wrong? Or is it actually an issue? If so, could you help us resolving it?

**Comment by v-MadhavC** [comment]
We are waiting for your response. If no response is received within the next couple of weeks, the issue will be closed.

**Comment by ayeshurun** [comment]
The issue is closed since no response was received.
