### ISSUE TITLE
Reload or Refresh automatically after detect an error

### ISSUE THREAD

**Issue by rodrigo-md** [microsoft/powerbi-client-react#5]
I've been working with PowerBI Embedded in some projects and I discovered that exists a common use case in this project. This is when the client stops the dedicated capacity at some hours to reduce costs and resume at another time.

I've noticed that an error is capture by this component or powerbi client, and displays a message to notify the user of what happened. But if the user keeps in the view without refreshing the page the error keeps displayed until the user hits the ok button and after that nothing is showing.

Is this a common scenario? do you consider that needs to be handled by this library?

**Comment by anant-k-singh** [comment]
This is currently not in the scope of this library.
You need to manually handle this scenario/error and call `report.refresh()`
