### ISSUE TITLE
PowerBIEmbed display issue on switching to different tab before the Power Bi report is loaded/rendered

### ISSUE THREAD

**Issue by kartickshaw** [microsoft/powerbi-client-react#51]
Steps to Reproduce the issue.
1. Click on React Navigation link that will load the embeded PowerBi report
2. Immediately move to a different tab on the browser (Before the report is loaded in step 1)
3. Come back to you application after some time (by the time report should have loaded)
4. Observed reported is not loaded as expected sometime showing empty body some time showing broken reports .

Note : If I am staying on the page till the report is rendered . Report generation is proper and there is no issue. Issue is occurring only when I am moving out of the page before Power BI report is fully generated

**Comment by v-MadhavC** [comment]
Thank you for reporting this issue. This is an old issue, is it still relevant?

**Comment by v-MadhavC** [comment]
We are waiting for your response. If no response is received within the next couple of weeks, the issue will be closed.

**Comment by ayeshurun** [comment]
The issue is closed since no response was received.
