### ISSUE TITLE
Using bootstrap mode causes exception related to bookmarks manager

### ISSUE THREAD

**Issue by wendylrichards** [microsoft/powerbi-client-react#52]
As per the readme I am using bootstrap mode on the component so that the PowerBI embed loading spinner is shown while I am fetching an access token in the background.

This causes the bookmarks manager to throw an exception when I call report.bookmarksManager.getBookmarks();

The exception relates to the bookmark manager accessing a property on its internal config object which seems to be a cut down version of of the embed config passed to the react component.

It seems that when the props of the react component are updated to contain the full embed config object that configuration is not updated on the bookmark manager.

If I comment out the bootstrap code and only load the react component when I have the full config then the problem does not occur.

**Comment by KotanaSai21** [comment]
Unable to repro the issue, If the issue is still relevant, please open a new issue with reproduction steps.
