### ISSUE TITLE
Default Slicer Values to be changed dynamically based on the selection of filters by users.

### ISSUE THREAD

**Issue by shivaprasad-manjunath** [microsoft/powerbi-client-react#53]
**Business Requirement**: Default Slicer Values to be changed dynamically based on the selection of filters by users.

**Challenge**: PowerBI does not support the default Slicer value changes based on filter change from front end.

**Workaround**: Pass the default values to slicers through an API from backend

**Issue**: While passing the values to slicer from API, default values are not updating in Power BI. Following are the procedure that we are following.

1. Created an API, which features the default value for every product
2. Based on the default values fetched, we create slicer configuration in the following format.
[{
"selector": {
"target": {
"table": "table_name",
"column": "column_name"
},
"$schema": "http://powerbi.com/product/schema#slicerTargetSelector"
},
"state": {
"filters": [{
"target": {
"table": "table_name",
"column": "column_name"
},
"$schema": "http://powerbi.com/product/schema#basic",
"operator": "In",
"values": ["domain.com"],
"filterType": 1,
"requireSingleSelection": true
}]
}
}]

3. Pass the above config as a slicers prop to the "PowerBIEmbed" component under "powerbi-client-react" (PowerBI react library). We are using the latest version (1.3.3)

**Comment by shivaprasad-manjunath** [comment]
@anant-k-singh any updates on this issue?

**Comment by WeslleyBorges** [comment]
Did you notice all the issues are open?

**Comment by ayeshurun** [comment]
The observed behavior is functioning as designed. For additional support, please contact your account manager or the [Fabric Support Team](https://support.fabric.microsoft.com/en-us/support/).
