### ISSUE TITLE
Update the report filters

### ISSUE THREAD

**Issue by WeslleyBorges** [microsoft/powerbi-client-react#54]
Is it possible to update the report filters like that?

![image](https://user-images.githubusercontent.com/26377031/135507457-80355ef1-ce51-4e94-bdaf-a91fc2e24d4c.png)

The image above is from pbi playground.

![image](https://user-images.githubusercontent.com/26377031/135507982-7d4ddb14-eee7-45b0-a792-d8ff77694d83.png)

In the image above im trying to update the report filters in React, but the second argument of the updateFilters function doesnt have the properties operator and values anymore.

Could someone please help me? Thank you all.

**Comment by KotanaSai21** [comment]
Filters in `updateFilters` api is of type `IFilter` and the interface of `IFilter` we don't have operator that's reason we are getting error. You can try below code

```
const filter: models.IBasicFilter = {
    $schema: "http://powerbi.com/product/schema#basic",
    target: {
        table: "Geo",
        column: "Region"
    },
    operator: "In",
    values: ["West", "Central"],
    filterType: 1
};

// Add the filter to the report's filters.
try {
    await report.updateFilters(models.FiltersOperations.Add, [filter]);
    console.log("Report filter was added.");
}
catch (errors) {
    console.log(errors);
}
```


Referneces: 
[Use filters when embedding a report in Power BI embedded analytics | Microsoft Learn](https://learn.microsoft.com/en-us/javascript/api/overview/powerbi/control-report-filters#update-filters)

**Comment by may-hartov** [comment]
supported IBasicFiltersOperators can be found here: https://learn.microsoft.com/en-us/javascript/api/powerbi/powerbi-models/basicfilteroperators
