### ISSUE TITLE
does the library support bookmarksManager.capture?

### ISSUE THREAD

**Issue by MateRadz** [microsoft/powerbi-client-react#55]
I cannot find it anywhere in the docs - currently I am using different wrapper of js power embedded api. I would like to move but I need to be assured bookmarksManager.capture is exposed.

**Comment by kostenickj** [comment]
it is, you need to get a reference to the report with getEmbeddedComponent

**Comment by Mingyang-Li** [comment]
Hey @kostenickj, is there a correct way to trigger or retrieve the values from `bookmarksManager.capture()` ?

I tried logging it within my `getEmbeddedComponent` prop for `<PowerBIEmbed />`, but I can't see any logs whatsoever.

I also tried logging it inside useeffects, still, nothjing shows up.

```tsx
export const Page = () => {
  // global state
  const {
    setPowerbiReportConfiguration,
    powerBIReportConfiguration,
    setPowerBiReport,
    powerBiReport,
  } = useAppStore();

  useEffect(() => {
    console.log(`PBI_REPORT_CHANGED`);
    powerBiReport
      ?.getFilters()
      .then((d) => console.log(`FILTERS => ${d}`))
      .catch((e) => console.warn(e));
  }, [powerBiReport]);

return (
  <PowerBIEmbed
    embedConfig={reportConfig}
    eventHandlers={eventHandlers}
    cssClassName={'h-full'}
    getEmbeddedComponent={(embeddedReport) => {
      const r = embeddedReport as Report;
      console.log(
        `r.bookmarksManager.capture() ==> ${r.bookmarksManager.capture()}`,
      );
      setPowerBiReport(embeddedReport as Report);
    }}
  />
  )
}

```
