### ISSUE TITLE
Access token

### ISSUE THREAD

**Issue by rubenberna** [microsoft/powerbi-client-react#59]
Hi,

In the demo we're fetching the token -- an essential key to render the embedded Power BI -- from a sample url in the mockSignIn function, but could you add information on how to get the token in a real case scenario? In this particular case, the Power BI is within an organization.

Thanks

**Comment by alaborderie** [comment]
Hi @rubenberna, did you find the answer to your question?

I'm currently trying to find the same information, and as much as I try I can't find a clear answer in Microsoft's docs.
If you found how we should get the accessToken, I'd love to have a quick explanation from you or anyone else :)

**Comment by navinrangar** [comment]
yeah i'm waiting for the same.

**Comment by KotanaSai21** [comment]
Refer to the React Samples code here [PowerBI-Developer-Samples/React-TS](https://github.com/microsoft/PowerBI-Developer-Samples/tree/master/React-TS). This is only applicable for Users Own Data ( Embed for your Organization scenario). 

For Apps own data, and using Service principal as authorization method, currently msal-react only supports public client applications. So, we need to use backend which is capable of keeping the secret. 
 So, workaround is to get the Embed Token from Azure Function.


1. Create a [HTTP Trigger function](https://learn.microsoft.com/en-us/azure/azure-functions/functions-create-function-app-portal) in azure portal and implement C# code to get the token using the client_credentials.
2. Get the function URL and in React App fetch the URL to get the embedUrl, Access Token for Embedding Report.

Feel free to Reach out if you face any problems with creating the function and code to get the token in azure portal.
