### ISSUE TITLE
createReport - Bump from #34

### ISSUE THREAD

**Issue by coding-totoro** [microsoft/powerbi-client-react#63]
Whats the ETA on support for createReport via this package?

**Comment by navinrangar** [comment]
i'm waiting for the same

**Comment by KotanaSai21** [comment]
`createReport` is now supported via powerbi-client-react package. Upgrade your package version `"powerbi-client-react": "^1.4.0"`. embedConfig  will be of type[ IReportCreateConfiguration](https://learn.microsoft.com/javascript/api/powerbi/powerbi-models/ireportcreateconfiguration). 

Feel free to reach out for any other queries.
