### ISSUE TITLE
Refresh an embedded report

### ISSUE THREAD

**Issue by AnthonyPhan** [microsoft/powerbi-client-react#64]
Hi,

We have a report where the data is updated every 10 minutes. 
Is there a recommended way to refresh the embedded power-bi report to reflect the new data? Right now we are updating the embedded URL prop on a timer to force it to re-render but this feels like a hack. 

Does the PowerBi react client offer a "native" why to do this?

**Comment by sunil-brillio** [comment]
@AnthonyPhan Please let me know if found any other way of doing this. I'm also looking for solution. Thanks

**Comment by KotanaSai21** [comment]
`refresh()` Api will refresh the powerbi-embedded report but currently there is no Api that implements recurrent actions.

Reference: 
[General operations in a Power BI embedded analytics application | Microsoft Learn](https://learn.microsoft.com/en-us/javascript/api/overview/powerbi/embedding-basic-interactions#refresh-a-report)
