### ISSUE TITLE
How to retain dates in UTC?

### ISSUE THREAD

**Issue by sairexes** [microsoft/powerbi-client-react#68]
Does anyone knows how to retain the dates in UTC instead of local time? What config do I need to use?

**Comment by v-MadhavC** [comment]
Hello, we have attempted to replicate the issue you mentioned, but we find that the UTC date and time remain unchanged, even after embedding the report using the package.

Could you please provide additional information?
     1. Are you utilizing any Power Query transformations to convert time from local to UTC?
     2. Is the UTC time conversion happening in your Power BI Desktop/Services environment as well, or does it occur only after 
         embedding the report?

**Comment by orshemesh16** [comment]
Closing since we didn't get a reply for few months.
