### ISSUE TITLE
Error while rendering powerbi using power-bi client in react application

### ISSUE THREAD

**Issue by v-sinhak** [microsoft/powerbi-client-react#70]
Getting the below error while rendering power bi. Please suggest any resolution for this error

![image](https://user-images.githubusercontent.com/68529674/175462260-f934a25e-0ffe-4cbe-bcef-62caf5b56c37.png)

powerbi' threw exception

Error: Error during server side rendering for module powerbi of type powerbi. NOTE: This error is only displayed in DEVELOPER mode. This won't affect PRODUCTION. This is a safety measure so developer can address issues that happen on the server. Please, address the following issue: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. at C:\onlinerepo\Msdyn365.Commerce.Online\node_modules\react-dom\cjs\react-dom-server.node.development.js:3736:30 at ReactDOMServerRenderer.render (C:\onlinerepo\Msdyn365.Commerce.Online\node_modules\react-dom\cjs\react-dom-server.node.development.js:3739:9) at ReactDOMServerRenderer.read (C:\onlinerepo\Msdyn365.Commerce.Online\node_modules\react-dom\cjs\react-dom-server.node.development.js:3395:29) at Object.renderToString (C:\onlinerepo\Msdyn365.Commerce.Online\node_modules\react-dom\cjs\react-dom-server.node.development.js:3954:27) at SafeRenderModule._doServerSideRender (C:\onlinerepo\Msdyn365.Commerce.Online\build\webpack:\Msdyn365.Commerce.Online\src\components\safe-render-module.tsx?d6f6:466:36) at SafeRenderModule._renderModule (C:\onlinerepo\Msdyn365.Commerce.Online\build\webpack:\Msdyn365.Commerce.Online\src\components\safe-render-module.tsx?d6f6:286:29) at SafeRenderModule.render (C:\onlinerepo\Msdyn365.Commerce.Online\build\webpack:\Msdyn365.Commerce.Online\src\components\safe-render-module.tsx?d6f6:183:27) at SafeRenderModule.makeComponentReactive (C:\onlinerepo\Msdyn365.Commerce.Online\build\webpack:\Msdyn365.Commerce.Online\node_modules\mobx-react\index.module.js?27cd:833:1) at SafeRenderModule.target.render (C:\onlinerepo\Msdyn365.Commerce.Online\build\webpack:\Msdyn365.Commerce.Online\node_modules\mobx-react\index.module.js?27cd:1092:1) at processChild (C:\onlinerepo\Msdyn365.Commerce.Online\node_modules\react-dom\cjs\react-dom-server.node.development.js:3171:18)

**Comment by KotanaSai21** [comment]
If the Issue still exists, please Open a new issue and provide proper repro steps and code snippet.
