### ISSUE TITLE
Export  PowerBI report to PDF,PPT or an Image

### ISSUE THREAD

**Issue by anmolmalik97** [microsoft/powerbi-client-react#71]
Hi team, I'm new to PowerBI and have used this library to embed one of the reports inside the react app.
I've checked through the issues and documentation but couldn't find any way to do it.

Any help would be highly appreciated.
Thanks in advance!

**Comment by BrianUribe6** [comment]
This might be a late reply, but for anyone that encounters this. You might want to look into [ExportToFile API](https://learn.microsoft.com/en-us/rest/api/power-bi/reports/export-to-file).

**Comment by KotanaSai21** [comment]
Follow these steps to export the report.

1. Sending an Export request- Send an export request. [Reports - Export To File - REST API (Power BI Power BI REST APIs) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/power-bi/reports/export-to-file)

2. Polling - Use polling to identify the status of your export and when the file will be ready from the response object which have percentComplete and status.

3. Getting the File - Once your report available, you can generate a blob response, and create a URL object from the blob and set it as href of link element. When user clicks the link, browser will download the file.

References:
[Export Power BI embedded analytics reports API - Power BI | Microsoft Learn](https://learn.microsoft.com/en-us/power-bi/developer/embedded/export-to#considerations-and-limitations)

**Comment by KotanaSai21** [comment]
Follow these steps to export the report.

1. Sending an Export request- Send an export request. [Reports - Export To File - REST API (Power BI Power BI REST APIs) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/power-bi/reports/export-to-file)

2. Polling - Use polling to identify the status of your export and when the file will be ready from the response object which have percentComplete and status.

3. Getting the File - Once your report available, you can generate a blob response, and create a URL object from the blob and set it as href of link element. When user clicks the link, browser will download the file.

References:
[Export Power BI embedded analytics reports API - Power BI | Microsoft Learn](https://learn.microsoft.com/en-us/power-bi/developer/embedded/export-to#considerations-and-limitations)

**Comment by Mingyang-Li** [comment]
Hey @may-hartov, is there any ways you can export reports that satisfies the following requirements:
1. The exported report uses the same filters applied from the embedded report
2. The exported report uses the same slicers applies from the embedded report

I've created an issue here to make it easier to track answers to my queries: https://github.com/microsoft/powerbi-client-react/issues/125
