### ISSUE TITLE
powerbi client react report designer

### ISSUE THREAD

**Issue by Innotech-Ahmad-Masoud** [microsoft/powerbi-client-react#73]
I need to build the reports via in my web app by using report designer? do we have something from power bi to support that

**Comment by KotanaSai21** [comment]
Only creating a report is supported in a web app. powerbi-client-react now supports createReport where you can create a report and save the report in your workspace.  embedConfig  will be of type[ IReportCreateConfiguration](https://learn.microsoft.com/javascript/api/powerbi/powerbi-models/ireportcreateconfiguration). 
Refer [Create a new Report](https://learn.microsoft.com/javascript/api/overview/powerbi/create-edit-report-embed-view?tabs=embed-for-your-customers#create-a-new-report) documentation.

Creating a paginated report is only supported in Power BI Desktop, Power BI Service and Power BI Report Builder. 
Refer [Create a paginated report](https://learn.microsoft.com/power-bi/visuals/paginated-report-visual) documentation.
