### ISSUE TITLE
Powerbi-client throw an error

### ISSUE THREAD

**Issue by zorrolisto** [microsoft/powerbi-client-react#76]
![image](https://user-images.githubusercontent.com/53353546/179790383-cc5837a5-1c4f-4956-94d9-daa00c9ea90c.png)

This error happen when is use the component powerbi-client-react but the user change to another view before it finish to load.  
Posted here because powerbi-client don't allow create issues.  
This error can be avoid with.   

```diff
powerbi.js -- line 6061
WindowPostMessageProxy.prototype.sendResponse = function (targetWindow, message, trackingProperties) {	        
    this.addTrackingProperties(message, trackingProperties);	        
    if (this.logMessages) {	            
        console.log(this.name + " Sending response:");	            
        console.log(JSON.stringify(message, null, '  '));	        
    }        
+    if(targetWindow){
+        targetWindow.postMessage(message, "*");            
+    }	        
-    targetWindow.postMessage(message, "*");	  
};
```

**Comment by bathan** [comment]
This problem still exists. Any hopes to get a fix?

**Comment by KotanaSai21** [comment]
Unable to repro. Can you please provide steps to repro this issue.

**Comment by raquelcarvalho** [comment]
This problem still exists. Any hopes to get a fix?

**Comment by raquelcarvalho** [comment]
@KotanaSai21 , Thanks! Well, I'm using the lib powerbi-client-react in version 1.4.0, which has the dependency "powerbi-client": "^2.21.1". As the fixed version is in beta, the lastest version is installed, which is 2.22.3 of powerbi-client.
So I keep getting the error. How could I overcome this?

**Comment by raquelcarvalho** [comment]
I got around the problem by using the paths option in the `tsconfig.json` file:

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "powerbi-client": ["node_modules/powerbi-client"]
    }
  }
}
```

This tells TypeScript to look for `powerbi-client` in my project's `node_modules` directory.
