### ISSUE TITLE
Token expire issue after 10 min. How to get token without refresh?

### ISSUE THREAD

**Issue by Sushmasrig** [microsoft/powerbi-client-react#77]
After every 10 min token is getting expired and giving 401, but it is not generating new tokens.
But after page refresh, a new token is generated and it is working fine. Is there any way to get a new token without page refresh. If possible any working example is really appreciated.

**versions**:
"powerbi-client-react": "^1.3.5",
"react": "^18.0.0",
node: v14.18.1
npm version: 6.14.15

    function getEmbeddedComponent() {
        return function (embeddedReport) {
            window.report = embeddedReport;
        };
    }

             <PowerBIEmbed   
                            embedConfig={{
                                type: 'report',
                                id: reportId,
                                embedUrl: `url here`,
                                accessToken: token,
                                tokenType: models.TokenType.Embed,
                            }}
                            cssClassName={'report-style-class'}
                            getEmbeddedComponent={getEmbeddedComponent()}
                        />

**Comment by khchan** [comment]
If you have an instance of the report you can follow the example [here](https://docs.microsoft.com/en-us/javascript/api/overview/powerbi/refresh-token) to add your own token refresh logic.

**Comment by Sushmasrig** [comment]
I added logic to make token API call after a certain interval of time, which resolved my issue.
