### ISSUE TITLE
How to add ARIA attributes like role and aria-label to powerbi element (iframe)?

### ISSUE THREAD

**Issue by vijayvinayaka** [microsoft/powerbi-client-react#81]

**Comment by KotanaSai21** [comment]
We have Javascript API to set the iframe title
Follow the below code to set the title to iframe in the powerbi-client-react demo app.
```
try {
    const title: string = "Embedded report";
    report.setComponentTitle(title);
    console.log("The <iframe> title was set to \"" + title + "\"");
}
catch (errors) {
    console.log(errors);
}
```

References: 
[Accessibility for your Power BI embedded analytics embedded solution | Microsoft Learn](https://learn.microsoft.com/en-us/javascript/api/overview/powerbi/accessibility)
