### ISSUE TITLE
Demo Install and Run Issues

### ISSUE THREAD

**Issue by jmcgroar** [microsoft/powerbi-client-react#82]
I've run into a couple of issues when installing and then running the Demo.

1. On the install of Demo, I'm seeing 4 warnings.

_npm WARN ts-loader@7.0.5 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN powerbi-client-react-demo@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})_

Are these to be expected or is there some corrective action I need to take?

2. When I run the Demo, I receive a lot (127) of compile errors on the file index.d.ts.  Here is a sample:

_Compiled with problems:

ERROR in F:\Development Projects\powerbi-client-react\demo\node_modules\@types\express-serve-static-core\index.d.ts

[tsl] ERROR in F:\Development Projects\powerbi-client-react\demo\node_modules\@types\express-serve-static-core\index.d.ts(102,68)
      TS1110: Type expected.

ERROR in F:\Development Projects\powerbi-client-react\demo\node_modules\@types\express-serve-static-core\index.d.ts

[tsl] ERROR in F:\Development Projects\powerbi-client-react\demo\node_modules\@types\express-serve-static-core\index.d.ts(102,77)
      TS1005: '}' expected._

Is this the result of a version conflict?

I'm using Visual Studio Code on Windows 10 with TSC 4.9.4 installed.

Thank you,

-Jeff

**Comment by bapat-atharva** [comment]
Not able to reproduce the first error, but for the second, please upgrade the demo package json to use latest typescript and ts-loader versions
`"ts-loader": "^9.4.2",`
`"typescript": "^4.9.4",`

**Comment by jmcgroar** [comment]
Atharva,

 

Thanks so much for responding to my issues.  I will try your suggestion and update the TS-related package versions tomorrow.

 

I found your project very helpful.  Nice work!

 

Thank you,

 

-Jeff
