### ISSUE TITLE
Page navigation is not working in embedded powerbi reports

### ISSUE THREAD

**Issue by ammuk679** [microsoft/powerbi-client-react#85]
Added the below setting configuration to PowerBIEmbed component
settings: {
				filterPaneEnabled: false,
				navContentPaneEnabled: true,
				layoutType: layoutType: models.LayoutType.MobilePortrait
			}
Still not able to see Navigation pane in mobile view/actual mobile device.

**Comment by KotanaSai21** [comment]
This is one of the Limitation for Mobile Layout in Embedded. Refer to [Embeddeding Report in Mobile Layout](https://learn.microsoft.com/en-us/javascript/api/overview/powerbi/mobile#limitations). 

As mentioned, you can use `setPage` and implement your own NavigationPane. Feel Free to Reach out for any other issues while implementing custom Pane.
