### ISSUE TITLE
Not able to export(visible) in PNG/PDF/PPTX from external libraries.

### ISSUE THREAD

**Issue by Sushmasrig** [microsoft/powerbi-client-react#87]
Power Bi react client has internal export functionalities, but for my use case, I want to use external export(Pdf/png/pptx) instead of internal. 
I used third-party libraries to export, everything is rendering correctly except the power bi client component. I am attaching the link for reference: 
https://stackblitz.com/edit/react-nyqusc?file=src%2FApp.js

    "html-to-image": "^1.11.11",
    "jspdf": "^2.5.1",
    "powerbi-client": "^2.19.1",
    "powerbi-client-react": "1.3.3",
    "powerbi-report-authoring": "1.1.3",
    "react": "17.0.2",
    "react-dom": "17.0.2"
    
    Node version: v14.18.1

 I also used other Pdf libraries but still power bi client component is not able to export(visible) in pdf and png.

**Comment by KotanaSai21** [comment]
Microsoft recommends using Export To File API for exporting PowerBI Report.

[Export To File](https://learn.microsoft.com/rest/api/power-bi/reports/export-to-file) REST API helps us to export the report. Refer [Export Power BI embedded analytics reports API ](https://learn.microsoft.com/en-us/power-bi/developer/embedded/export-to) documentation.

We also have ani API `report.print()` this method prints only the active page of report invoking `windows.print()` on embedded iframe component.

Feel Free to reach out if you have any other queries.

**Comment by Sushmasrig** [comment]
Thank you for sharing this information. report. print() is working fine for me.

**Comment by Sushmasrig** [comment]
I have checked the documentation for .pptx and .png but it will be helpful if there is any working example or any sample code for reference.

**Comment by KotanaSai21** [comment]
From the [documentation](https://learn.microsoft.com/power-bi/developer/embedded/export-to), export job consists of four steps.


1. Sending an Export request - Make a REST API call to get the `exportId` ( [ExportToFile](https://learn.microsoft.com/en-us/rest/api/power-bi/reports/export-to-file) or [ExportToFileInGroup](https://learn.microsoft.com/en-us/rest/api/power-bi/reports/export-to-file-in-group))
2. Polling - Make a call to identify whether the report is ready to download. ( [GetExportToFileStatus](https://learn.microsoft.com/en-us/rest/api/power-bi/reports/get-export-to-file-status) or [GetExportToFileStatusInGroup](https://learn.microsoft.com/en-us/rest/api/power-bi/reports/get-export-to-file-status-in-group) )
3. Getting the File - From polling, you get to know the export state. Once Export state is succeeded, make a call to get the file. ([GetFileof ExportToFile](https://learn.microsoft.com/en-us/rest/api/power-bi/reports/get-file-of-export-to-file) or [GetFileofExportToFileInGroup](https://learn.microsoft.com/en-us/rest/api/power-bi/reports/get-file-of-export-to-file-in-group))
4. Once you get the file stream, download the file.

Refer to this [Export PowerBI Embedded Report using Export To File APIs](https://gist.github.com/KotanaSai21/63e585284b1f5045ef2a154b76ea380f) gist file.

Feel free to reach out if you have any other queries.

**Comment by Sushmasrig** [comment]
I tried as you mentioned in your code
URL: `https://api.powerbi.com/v1.0/myorg/reports/{myReportId}/ExportTo`.
Payload: {"format":"PPTX","powerBIReportConfiguration":{}}  
Http Error: 403.
I even checked my accessToken and reportId are being passed correctly but still getting 403 error.

**Comment by KotanaSai21** [comment]
@Sushmasrig , 

To use `ExportToFile` API, reports must reside in Premium or Embedded Capacity. Refer to [Limitations](https://learn.microsoft.com/en-us/power-bi/developer/embedded/export-to#considerations-and-limitations) documentation and verify.
