### ISSUE TITLE
LayoutReport does not update with new settings with function updateSettings(settings);

### ISSUE THREAD

**Issue by nirjhar18** [microsoft/powerbi-client-react#9]
Here is the code where I am using Power BI react component to render a blank report and then calling an action on loaded event handler. Action onLoaded fetches some JSON data and then create visuals on the report and then call renderVisuals with new settings. It looks like UpdateSettings function does not change the coordinates neither it changes the width/height correctly on resizing that I am trying to do. Here is the code for the component.

To look into actions, I am added the whole project on GitHub - https://github.com/nirjhar18/power-bi-updatesettings

`class EmbedChart extends React.Component {
  componentDidMount() {
    window.addEventListener(
      "resize",
      debounce((e) => {
        this.updateDimensions();
      }, 1000)
    );
  }
  updateDimensions = () => {
    this.props.actions.renderVisualsResize();
  };
  componentWillUnmount() {
    window.removeEventListener("resize", this.updateDimensions);
  }

  render() {
    return (
      <>
        <PowerBIEmbed
          embedConfig={{
            type: "report", // Supported types: report, dashboard, tile, visual and qna
            id: REPORT_ID,
            embedUrl: EMBED_URL,
            accessToken: EMBED_TOKEN,
            tokenType: models.TokenType.Embed,
            permissions: models.Permissions.All,
            viewMode: models.ViewMode.viewMode,

            settings: {
              panes: {
                filters: {
                  expanded: false,
                  visible: true,
                },
              },
            },
          }}
          eventHandlers={
            new Map([
              [
                "loaded",
                () => {
                  this.props.actions.loadCharts();
                },
              ],
              ["rendered", () => {}],
              [
                "error",
                function (event) {
                  console.log(event.detail);
                },
              ],
            ])
          }
          cssClassName={
            window.innerWidth > 1000
              ? "report-style-class"
              : "report-style-class-2"
          }
          getEmbeddedComponent={(embedObject) => {
            this.props.actions.getEmbeddedReport(embedObject);
          }}
        />
      </>
    );
  }
}`

**Comment by anant-k-singh** [comment]
I see you are trying to create new visuals, arrange them in a custom layout and apply this as settings using the `report.updateSettings()` method.
On executing your code, I ran into this error:
![image](https://user-images.githubusercontent.com/22440924/89519507-1b6ac780-d7fa-11ea-9a17-10d97adf2d81.png)

Please check if you are using the **active page** to create the new visuals. (You should search for active page by iterating over the list of report's pages)

After fixing the active page issue, new visuals were created and the custom layout was applied as expected via `LayoutShowcaseState.layoutReport.updateSettings(settings);` in chartAction.js

![image](https://user-images.githubusercontent.com/22440924/89520717-e9f2fb80-d7fb-11ea-950e-dc0068f1e893.png)
Note: This sample report is embedded using [PowerBI Embedded Playground](https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html)

**Comment by nirjhar18** [comment]
Hi Anant, I just updated the Github with report id and token that I am using. The token is valid for one hour but you can check in the code that I am creating the visuals with x and y coordinates as I need. The report Id I am using pages[0] is always the active page.

Also, I have an event listener on resizing. On resizing, I change the layout to two columns and call Render Visuals function but update settings does not change the layout columns
![IssueTwoColumns](https://user-images.githubusercontent.com/4294894/89534863-9a90d900-d7c3-11ea-8269-5f855c858c39.PNG)
