### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by nahcyrret** [microsoft/powerbi-client-react#90]
Compiled with problems:
×
ERROR in C:\GitHub\powerbi-client-react-master\demo\node_modules\@types\node\ts4.8\test.d.ts
[tsl] ERROR in C:\GitHub\powerbi-client-react-master\demo\node_modules\@types\node\ts4.8\test.d.ts(680,34)
      TS1005: '?' expected.
ERROR in C:\GitHub\powerbi-client-react-master\demo\node_modules\@types\node\ts4.8\test.d.ts
[tsl] ERROR in C:\GitHub\powerbi-client-react-master\demo\node_modules\@types\node\ts4.8\test.d.ts(681,17)
      TS1005: ':' expected.
ERROR in C:\GitHub\powerbi-client-react-master\demo\node_modules\@types\node\ts4.8\test.d.ts
[tsl] ERROR in C:\GitHub\powerbi-client-react-master\demo\node_modules\@types\node\ts4.8\test.d.ts(682,17)
      TS1005: ',' expected.
ERROR in C:\GitHub\powerbi-client-react-master\demo\node_modules\@types\node\ts4.8\test.d.ts
[tsl] ERROR in C:\GitHub\powerbi-client-react-master\demo\node_modules\@types\node\ts4.8\test.d.ts(685,34)
      TS1005: '?' expected.
...

I got the above errors after running "npm run demo". Are there really that syntax errors in test.d.ts? How to fix this problem?

**Comment by KotanaSai21** [comment]
Hello @nahcyrret , Please Upgrade the demo `package.json` to latest typescript and ts-loader versions.
```
"ts-loader": "^9.4.2",
"typescript": "^4.8.4",
```

Feel free to reach out if you have any other queries.

**Comment by nahcyrret** [comment]
![image](https://user-images.githubusercontent.com/39899353/230316838-f7222e84-e1d1-4d0e-ad1e-afe042cf1440.png)

I still got the errors after updating the versions.

**Comment by nahcyrret** [comment]
![image](https://user-images.githubusercontent.com/39899353/230317370-10de01fb-ecd7-49e8-b71d-5f22f29deb1b.png)

I still got the errors after updating the versions as shown.

**Comment by nahcyrret** [comment]
![image](https://user-images.githubusercontent.com/39899353/230318230-f62a35cb-4342-4ee9-9401-6c48521ce6a5.png)

I still got the errors after updating the versions as shown.

**Comment by KotanaSai21** [comment]
These are also the same version issues and should be fixed. Try reinstalling the node-modules. If still facing the same issue, please provide more context to repro the issue.

**Comment by nahcyrret** [comment]
I just installed the Latest LTS Version: 18.15.0 (includes npm 9.5.0) from
https://nodejs.org/en/download
