### ISSUE TITLE
incorrect width on `displayArea` when showing scrollbar

### ISSUE THREAD

**Issue by kitsunekyo** [microsoft/powerbi-client-react#91]
<img width="440" alt="image" src="https://user-images.githubusercontent.com/8297816/232717218-456b9710-19fc-4679-957a-7d07c00d7dcb.png">

in our usecase we have a 2 column layout, where an embedded powerbi report is displayed with `fitToWidth`. it works well, until the report needs to scroll. the scroll overflow is applied within the embed (iframe) on the `displayAreaContainer`. so this is completely out of our control.

in the example above, the iframe itself is `800px`wide. on overflow, the `displayArea` element in the iframe is suddenly only `773px`wide (applied via inline styles, by the embed code). which leads to this massive gap. 

i would have looked into the source, to find and propose a solution myself, but the embed code is apparently closed source and i cant create issues on the core js library.

**Comment by v-MadhavC** [comment]
Thank you for reporting this issue. This is an old issue, is it still relevant?

**Comment by kitsunekyo** [comment]
I've left the related project in the meantime, so I have no way of checking. it was an issue till the end, but has no prio for my anymore. thank you

**Comment by ayeshurun** [comment]
Thank you for reporting this issue. We closed the issue because it's old.
