### ISSUE TITLE
Seeing error "Embed URL is invalid for this scenario" when trying to loan any report in the embed component

### ISSUE THREAD

**Issue by msnyder-msft** [microsoft/powerbi-client-react#94]
We are trying to embed a report in our react app but are consistently getting blocked by this error "**Embed URL is invalid for this scenario. Please use Power BI REST APIs to get the valid URL**". It doesn't seem to matter how we modify the URL, it won't load no matter what. When I remove the `autoAuth` QSP then it just shows a loading indicator forever.

I got the URL by going to the PowerBI report and selecting the Embed option and pasting that URL into my code.
![image](https://user-images.githubusercontent.com/57726991/236272777-de3b2dd3-9ec4-4d6d-a99a-64cecbbebd58.png)

We already had code that was working with this report a few months back on this same package version but we had put it on the shelf and now when we came back it no longer is working despite not making any changes to it on our side. This leads me to believe it might be some kind of service side change that is causing the issue but if someone has other ideas on how to troubleshoot or things to try I would be open to any suggestions.

Embed snippet
```ts
import { PowerBIEmbed } from 'powerbi-client-react';

const reportUrl = 'https://<tenantDomain>.powerbi.com/reportEmbed?reportId=<reportId>&autoAuth=true&ctid=<tenantId>';
return (
    <div className={classNames.root}>
        <PowerBIEmbed
            embedConfig={{
                type: 'report',
                embedUrl: reportUrl,
            }}
        />
    </div>
);
```

Stats:
Package version 1.3.5 (also tested with 1.4.0)

Screenshot
![image](https://user-images.githubusercontent.com/57726991/236271654-a55a33b8-f42c-44b7-be71-6313b9ecac8a.png)

**Comment by may-hartov** [comment]
This issue is not related to powerbi-client-react repository, seems to be a user error.
The correct way to generate the embed url is not to have it static in the code, but use a [REST API to GET the report](https://learn.microsoft.com/en-us/rest/api/power-bi/reports/get-report-in-group#examples) using Power BI public REST APIs,. This is due to the fact the embed URL may change and contain some parameters that are required for the report render.

You can check out our [developer samples ](https://github.com/microsoft/PowerBI-Developer-Samples) to see how we fetch the embed URL

**Comment by msnyder-msft** [comment]
Thanks! The hard coded URL is a temporary thing just to see the report show up. But let me give that a try. 
Is it true that we need to pass the access token for the user even to show the report? In the past we were somehow getting away without having to do that but I see in the examples that they always pass the token to the embed component so perhaps that is also causing this?

**Comment by may-hartov** [comment]
Yes, the token most be provided (access token or embed token)

**Comment by NOELSAJO7** [comment]
Is there any way, I can embed the report without the access token as I want the report to be accessible to a particular group of people with autoAuth. Because having a bearer token will let anyone with it to access the report. 
Thank you

**Comment by aicest** [comment]
This problem occurs in `powerbi-client@2.23.0` and can be mitigated by installing `powerbi-client@2.22.4`.

Details: `powerbi-client@2.23.0` has an `allowedPowerBiHostsRegex` regex that uses the 'g' flag, which causes it to remember where the last successful match was, and therefore sometimes returns true and sometimes false.

**Comment by aicest** [comment]
This problem occurs in `powerbi-client@2.23.0` and can be mitigated by installing `powerbi-client@2.22.4`.

More: `powerbi-client@2.23.0` has an `allowedPowerBiHostsRegex` regex that uses the `g` flag, which causes it to remember where the last successful match was, and therefore sometimes returns `true` and sometimes `false`.

**Comment by tharakatk** [comment]
> This problem occurs in `powerbi-client@2.23.0` and can be mitigated by installing `powerbi-client@2.22.4`.
> 
> More: `powerbi-client@2.23.0` has an `allowedPowerBiHostsRegex` regex that uses the `g` flag, which causes it to remember where the last successful match was, and therefore sometimes returns `true` and sometimes `false`.

Thank you . Yes downgrading to powerbi-client@2.22.4 works for me.

**Comment by Rohith-Rao** [comment]
> This problem occurs in `powerbi-client@2.23.0` and can be mitigated by installing `powerbi-client@2.22.4`.
> 
> More: `powerbi-client@2.23.0` has an `allowedPowerBiHostsRegex` regex that uses the `g` flag, which causes it to remember where the last successful match was, and therefore sometimes returns `true` and sometimes `false`.

thanks, this worked

**Comment by NOELSAJO7** [comment]
> This problem occurs in `powerbi-client@2.23.0` and can be mitigated by installing `powerbi-client@2.22.4`.
> 
> More: `powerbi-client@2.23.0` has an `allowedPowerBiHostsRegex` regex that uses the `g` flag, which causes it to remember where the last successful match was, and therefore sometimes returns `true` and sometimes `false`.

is there any solution for powerbi-client-react the library specifically for react

**Comment by KotanaSai21** [comment]
The issue has been fixed with the new version release of powerbi-client [v2.23.1 ](https://www.npmjs.com/package/powerbi-client/v/2.23.1).  

Install the latest version and let us know if you still face the same issue.

**Comment by Removable** [comment]
> The issue has been fixed with the new version release of powerbi-client [v2.23.1 ](https://www.npmjs.com/package/powerbi-client/v/2.23.1).powerbi-client v2.23.1 新版本已修复了该问题。
> 
> Install the latest version and let us know if you still face the same issue.安装最新版本，如果仍遇到同样的问题，请告诉我们。

It works for me! thx!

**Comment by fadingNA** [comment]
> The issue has been fixed with the new version release of powerbi-client [v2.23.1 ](https://www.npmjs.com/package/powerbi-client/v/2.23.1).
> 
> Install the latest version and let us know if you still face the same issue.

2.23.1 worked for me too thanks!

**Comment by burakgumusfb** [comment]
I had same issue. Thanks for v.2.23.1

**Comment by ciprian-dragomir** [comment]
I had a different error message (`Invalid embed URL detected. Either URL hostname or protocol are invalid. Please use Power BI REST APIs to get the valid URL`), though looks like the same underlying issue. Confirming `v2.23.1` fixed it for me as well. Thanks!

**Comment by pravin3102** [comment]
I am still facing this issue can someone help me with this?
![Screenshot from 2024-04-12 13-08-09](https://github.com/microsoft/powerbi-client-react/assets/55386426/d178eebb-919f-4958-bc32-fbcecc4c88dc)

**Comment by Removable** [comment]
> I am still facing this issue can someone help me with this? I am using v2.23.1 and migrated to react 18 ![Screenshot from 2024-04-12 13-08-09](https://private-user-images.githubusercontent.com/55386426/321902424-d178eebb-919f-4958-bc32-fbcecc4c88dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDgzNTEsIm5iZiI6MTcxMjkwODA1MSwicGF0aCI6Ii81NTM4NjQyNi8zMjE5MDI0MjQtZDE3OGVlYmItOTE5Zi00OTU4LWJjMzItZmJjZWNjNGM4OGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA3NDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYTJkNTA0YzQwZGEwMzc1YmE0NTAxY2ViZmY4ZmE2ODBjNDY3OGE4OTc2Y2M3OTkzMzY3ZGRlYjIyZTJjMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BCsNExezwb01Sxbb-IMxEwbQe8DF82BeAwTA8AzlXLA)

Can you please show a screenshot of the `dependencies` part in your `package.json` file?

**Comment by pravin3102** [comment]
![image](https://github.com/microsoft/powerbi-client-react/assets/55386426/74e2f34d-88d4-481b-a0b6-643b846c17b5)

**Comment by Removable** [comment]
> ![image](https://private-user-images.githubusercontent.com/55386426/321906153-74e2f34d-88d4-481b-a0b6-643b846c17b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDg2MjYsIm5iZiI6MTcxMjkwODMyNiwicGF0aCI6Ii81NTM4NjQyNi8zMjE5MDYxNTMtNzRlMmYzNGQtODhkNC00ODFiLWEwYjYtNjQzYjg0NmMxN2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA3NTIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYmZjZmM1OTUyNjU0NDMzMjgwMzdkMzI2OTRkNzVkZTAyNDIzYTFhYjEwMzEzMjY3NWEwZTQ0ZDY2NDk3MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.igLy6Ink1CJYjhndzPXJD48c2M1iRelulmj63jdwe_I)

Hmm... it seems nothing special. Maybe you can try deleting the node modules folder and the package.lock.json file, then run `npm install` to reinstall all the packages. I don't know if it helps but have a try. 😃

**Comment by pravin3102** [comment]
> > ![image](https://private-user-images.githubusercontent.com/55386426/321906153-74e2f34d-88d4-481b-a0b6-643b846c17b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDg2MjYsIm5iZiI6MTcxMjkwODMyNiwicGF0aCI6Ii81NTM4NjQyNi8zMjE5MDYxNTMtNzRlMmYzNGQtODhkNC00ODFiLWEwYjYtNjQzYjg0NmMxN2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA3NTIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYmZjZmM1OTUyNjU0NDMzMjgwMzdkMzI2OTRkNzVkZTAyNDIzYTFhYjEwMzEzMjY3NWEwZTQ0ZDY2NDk3MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.igLy6Ink1CJYjhndzPXJD48c2M1iRelulmj63jdwe_I)
> 
> Hmm... it seems nothing special. Maybe you can try deleting the node modules folder and the package.lock.json file, then run `npm install` to reinstall all the packages. I don't know if it helps but have a try. 😃

no luck
