### ISSUE TITLE
Back button on paginated report goes to blank iframe

### ISSUE THREAD

**Issue by alessandro-hic** [microsoft/powerbi-client-react#95]
When viewing paginated report and pressing the back button, the action is passed to one of the 2 Iframes that are created, obtaining a white page, only when pressed again goes back correctly to the intended page.

I've tested both on my prod project and on a empty boilerplate project 
```
"powerbi-client-react": "^1.4.0",
react": "^18.2.0",
react-dom": "^18.2.0",
react-router-dom": "^6.11.2",
react-scripts": "5.0.1",
web-vitals": "^2.1.4"
```

**Comment by rad10wave** [comment]
We have identified the issue and added it in our backlog.

**Comment by ayeshurun** [comment]
Thank you for reporting this issue. We closed the issue because it's old.
