### ISSUE TITLE
Feedback when hiding the report filter is ambiguous

### ISSUE THREAD

**Issue by josea-xela** [microsoft/powerbi-client-react#97]
Message written to the 'display message' field when hiding the report filter is ambiguous

File: React\Demo\src\DemoApp.tsx
line: 126

Message says: 'Filter pane is hidden'.  

This could be misunderstood as a warning that the filter pane is not visible. The message should be that the 'filter pane has been hidden' instead.

**Comment by ayeshurun** [comment]
Thank you for your feedback. We will review your recommendation and if appropriate we will implement the necessary changes.
