### ISSUE TITLE
getSlicers() on class Page return type incorrect

### ISSUE THREAD

**Issue by m2icd** [microsoft/powerbi-client-react#99]
I noticed getSlicers() is declared to return Promise<IVisual[]> but in reality, like getVisuals(), it returns Promise<VisualDescriptor[]>. I can make successful calls like getSlicerState() and exportData() even though my typescript is telling me I shouldn't be able to.

**Comment by v-MadhavC** [comment]
We tried to reproduce this issue, but we're not facing typescript error while using either getSlicers() or getSlicerState() API.  We tried using the API in our [Developer Sandbox typescript editor](https://playground.powerbi.com/en-us/dev-sandbox) and not facing any errors.

![image](https://github.com/microsoft/powerbi-client-react/assets/126773262/c1082368-fe32-49f0-8cd4-715d50d96cde)

![image](https://github.com/microsoft/powerbi-client-react/assets/126773262/7bfe5caa-2ad4-41f8-abe7-811f1ad24051)

Please provide additional details regarding how you are using these methods and some code snapshots can help us better understand the issue.

**Comment by may-hartov** [comment]
Unable to reproduce the issue
